### ISSUE TITLE
Adding synonymous expression

### ISSUE THREAD

**Issue by arjunmenon** [yb66/tickle#10]
Hey man

If you do `Tickle.parse('day after tomorrow')` it parses it as `tomorrow`.
But if you do `Tickle.parse('2 days from now')` it works just fine.

Was wondering, if there is some way to add synonymous expressions, training the parser what expressions can be similar.
Or anyway to get this to work?

**Comment by yb66** [comment]
Hi

I saw this on the Chronic list too. This relies on Chronic so it's possibly better suited there, but if you supply a spec then at least someone can try coding against it.

Regards,
iain
