### ISSUE TITLE
tickle (>= 1.1.1, ~> 1.1) was resolved to 1.1.1, which depends on       chronic (~> 0.2.3)

### ISSUE THREAD

**Issue by angelacode** [yb66/tickle#19]
I seem to be having a problem:

```
tickle (>= 1.1.1, ~> 1.1) was resolved to 1.1.1, which depends on
      chronic (~> 0.2.3)
```

I need to use chronic 0.10.2 but I keep getting this error.

**Comment by yb66** [comment]
Have you tried using the v2.0.0.rc1 tag? It's up on Rubygems too. It definitely uses Chronic 0.10.2

iain
