### ISSUE TITLE
uninitialized constant Module::Numerizer

### ISSUE THREAD

**Issue by angelacode** [yb66/tickle#6]
irb(main):004:0> Tickle.parse('every day')
NameError: uninitialized constant Module::Numerizer

**Comment by angelacode** [comment]
did bundle install with gem file and got this error.

**Comment by yb66** [comment]
Hi @angelacode

Which version did it install? (`bundle show rspec`)

regards,
iain

**Comment by yb66** [comment]
No response and this was fixed since before version 1.0.0. Closed.
