### ISSUE TITLE
how do I set/know the Time Zone

### ISSUE THREAD

**Issue by timfong888** [yb66/tickle#7]
I want to be able to explicitly check for the next occurrence based on a time-zone.

It looks like the time-zone for `next_occurrence` is what the time-zone was explicitly set when it was set.

It seems like, if I have users from different time-zones, I would need to always normalize the next_occurrence to something like UTC, so all are set at UTC.

Is that done basically by converting the intended time for the user (they may want every day at 10:00AM PST), to convert that time to UTC and use that as the starting time?

**Comment by yb66** [comment]
Hi @timfong888 

To be honest, I don't know the answer to that. I'll look into it.

regards,
iain

**Comment by yb66** [comment]
Hi again @timfong888 

Sorry for the delay. There is an example for this [https://github.com/yb66/tickle/blob/v1.0.2/examples.rb](here). I hope that clears things up.

regards,
iain
